{{- if .Values.cronjobs }}
{{- range $name, $cronjob := .Values.cronjobs }}
{{- if $cronjob.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}
  labels:
    {{- include "app.labels" $ }}
spec:
  schedule: "{{ $cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $name }}-container
            image: {{ $cronjob.image }}
            imagePullPolicy: {{ $cronjob.imagePullPolicy | default "IfNotPresent" }}
            env:
              {{- range $key, $value := $cronjob.env }}
              - name: {{ $key }}
                value: "{{ $value }}"
              {{- end }}
            command: {{ toJson $cronjob.command | default (quote "echo 'No command specified'") }}
            args: {{ toJson $cronjob.args | default (quote "[]") }}
          restartPolicy: {{ $cronjob.restartPolicy | default "OnFailure" }}
{{- end }}
{{- end }}
{{- end }}
