{{- if and .Values.persistence.enabled .Values.persistence.volumes }}
{{- range .Values.persistence.volumes }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ .size | default "5Gi" }}
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .storageClass | default "local-path" }}
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy | default "Retain" }}
  volumeMode: Filesystem
  hostPath:
    path: {{ .hostPath | default "/mnt/data/{{ .name }}" }}
---
{{- end }}
{{- end }}
{{- end }}
