{{- if and .Values.persistence.enabled .Values.persistence.claims }}
{{- range .Values.persistence.claims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .size | default "5Gi" }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass }}
  {{- else }}
  storageClassName: ""
  {{- end }}
{{- end }}
{{- end }}
