{{- if .Values.secrets }}
  {{- range .Values.secrets }}
    {{- if and .name .data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
